require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - Rakefile
    - Guardfile
    - bin/*
    - config/skeleton/Dockerfile.ruby
    - node_modules/**/*
  TargetRubyVersion: 2.6.3

Metrics/BlockLength:
  ExcludedMethods:
    - class_methods
    - namespace
    - context
    - describe
    - shared_examples
    - shared_examples_for
    - shared_context
    - define
    - factory
    - include_context
    - let

Metrics/LineLength:
  IgnoredPatterns:
    - '(\A|\s)#'
    - '\A\s{2,}scope'
  Max: 120

Rails/Output:
  Exclude:
    - db/seeds.rb

RSpec/ExampleWithoutDescription:
  EnforcedStyle: disallow

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 4
